import type { Translation } from './types';

export const en: Translation = {
  locale: 'en', localeLabel: 'English', tagline: 'Soluções digitais para o seu negócio.',
  nav: { home: 'Home', services: 'Services', packages: 'Packages', about: 'About', portfolio: 'Portfolio', contact: 'Contact' },
  footer: { navigation: 'Navigation', services: 'Services', servicesList: [{ label: 'Web Design', id: 'websites' }, { label: 'Google Business', id: 'google' }, { label: 'WhatsApp Business', id: 'whatsapp' }, { label: 'Facebook & Instagram', id: 'social' }, { label: 'Online reservations', id: 'reserveringen' }, { label: 'SEO', id: 'seo' }, { label: 'Maintenance', id: 'onderhoud' }], contact: 'Contact', privacy: 'Privacy policy', cookies: 'Cookie policy', rights: 'All rights reserved.' },
  common: { analysisCta: 'Free digital analysis', viewWork: 'View our work', viewServices: 'View all services', viewPackages: 'View all packages', learnMore: 'More about Morabeza Tech', startProject: 'Start your project', contactUs: 'Get in touch', mostChosen: 'Most popular', languageSelector: 'Choose language', menuOpen: 'Open menu', menuClose: 'Close menu', next: 'Next', backHome: 'Back to home', conceptNote: 'All examples are concept projects, not real client cases.', location: 'Praia, Cabo Verde', email: 'info@morabezatech.com' },
  home: {
    eyebrow: 'Digital solutions for modern businesses', title: 'Grow your business with smart digital solutions.', intro: 'Morabeza Tech helps businesses and entrepreneurs in Cabo Verde improve their online visibility, reach more customers and grow digitally.', supportingLine: ['Web Design', 'Online Visibility', 'Automation', 'Digital Growth'],
    positioningEyebrow: 'More than a website', positioningTitle: 'Digital clarity that moves your business forward.', positioningIntro: 'Morabeza Tech develops digital solutions that help businesses look more professional online, become easier to reach and connect with more customers.', principles: [{ number: '01', title: 'Professional design', copy: 'A clear experience that builds trust.' }, { number: '02', title: 'Smart technology', copy: 'The right digital route for your business.' }, { number: '03', title: 'Built for results', copy: 'Be visible online and make contact easier.' }],
    servicesEyebrow: 'What we do', servicesTitle: 'Digital solutions with a clear purpose.', servicesIntro: 'From your first website to a stronger Google presence: we bring together the digital elements your customers need.',
    portfolioEyebrow: 'Concept studies', portfolioTitle: 'Work that speaks for itself.', portfolioIntro: 'A look at how a digital experience can be shaped for different businesses. These examples are clearly labelled as concept projects.',
    processEyebrow: 'Our process', processTitle: 'From idea to a digital experience that works.', processIntro: 'A clear approach shaped around your business, audience and goals.', process: [{ number: '01', title: 'Analysis', copy: 'We look at your business, audience and current online presence.' }, { number: '02', title: 'Strategy', copy: 'We define what is needed to present your business online clearly and effectively.' }, { number: '03', title: 'Design', copy: 'We design a modern, clear digital experience that fits your brand.' }, { number: '04', title: 'Development', copy: 'We build a fast, secure and responsive website.' }, { number: '05', title: 'Launch & support', copy: 'We publish, test and remain available for optimisation and maintenance.' }],
    analysisEyebrow: 'No obligation', analysisTitle: 'Start with a free digital analysis.', analysisIntro: 'We review your Google presence, website, WhatsApp, social media, online reviews and digital visibility. You then receive practical recommendations.', analysisStatus: 'Free analysis', analysisItems: ['Google', 'Website', 'WhatsApp', 'Social media', 'Online reviews', 'Digital visibility'], analysisNote: 'A practical view of where your business stands online and where opportunities may be.',
    packagesEyebrow: 'Packages', packagesTitle: 'A clear starting point for every type of business.', packagesIntro: 'Every business is different. We shape the final solution around your needs, goals and budget.', monthlySupport: 'Monthly maintenance and digital support are also available.',
    aboutEyebrow: 'Morabeza Tech CV', aboutTitle: 'Technology with a human touch.', aboutIntro: 'Morabeza Tech is a digital solutions company focused on businesses and entrepreneurs in Cabo Verde. We help businesses become more visible online and make it easier for customers to discover, trust and contact them.', aboutMark: 'Local knowledge. Digital possibilities.', aboutLocation: 'Praia · Cabo Verde', mockupEyebrow: 'Digital analysis', mockupValue: '+ clarity',
    finalEyebrow: 'Ready for the next step?', finalTitle: 'Ready to put your business in a stronger position online?', finalIntro: 'Tell us what you want to achieve. We will think with you about a digital solution that fits your business, goals and budget.'
  },
  servicesPage: {
    eyebrow: 'Services', title: 'Digital solutions that move your business forward.', intro: 'From a professional website to stronger online visibility: we build the digital foundation that helps customers find, trust and contact your business.', sectionEyebrow: 'How we can help', sectionTitle: 'The right elements brought together in one clear experience.', sectionIntro: 'Every business needs something different. We start by understanding where your customers get stuck and which digital solution fits.',
    services: [
      { number: '01', title: 'Professional websites', short: 'A fast, responsive and clear digital foundation for your business.', detail: 'Your website is often the first contact with your business. We build an experience that fits your brand and makes it easy to get in touch.', items: ['Business websites', 'Landing pages', 'Responsive development', 'Performance', 'Maintenance'], tone: 'blue' },
      { number: '02', title: 'Google Business & Google Maps', short: 'Make it easier for customers to find your business when they search.', detail: 'Many customers start with Google. We help present your business information clearly and professionally so people know how to reach you.', items: ['Google Business', 'Google Maps', 'Local visibility', 'Business information'], tone: 'cyan' },
      { number: '03', title: 'WhatsApp Business', short: 'Make contact easier with a clear route to WhatsApp.', detail: 'A well-structured contact flow gives potential customers fewer reasons to drop off.', items: ['WhatsApp Business', 'Contact buttons', 'Lead generation', 'Clear contact route'], tone: 'gold' },
      { number: '04', title: 'Facebook & Instagram', short: 'A consistent digital presence that builds trust.', detail: 'We help your social presence connect professionally with your website and Google profile.', items: ['Facebook', 'Instagram', 'Digital presence', 'Content structure'], tone: 'violet' },
      { number: '05', title: 'Online appointments & reservations', short: 'Make it easier to request an appointment, table, room or vehicle.', detail: 'We think through an online route that matches the way your business works.', items: ['Online appointments', 'Reservations', 'Request flows', 'Contact forms'], tone: 'blue' },
      { number: '06', title: 'Reviews & online reputation', short: 'Give potential customers more confidence in your business.', detail: 'Reviews help people form an impression. We consider the digital places where reputation is part of the customer experience.', items: ['Online reviews', 'Reputation', 'Review flow', 'Trust'], tone: 'cyan' },
      { number: '07', title: 'SEO & online visibility', short: 'A strong digital foundation makes it easier to be found.', detail: 'We pay attention to structure, information and local context for businesses in Cabo Verde.', items: ['SEO', 'Online visibility', 'Local context', 'Information architecture'], tone: 'gold' },
      { number: '08', title: 'Website maintenance & support', short: 'Keep your digital foundation clear, current and useful.', detail: 'Monthly maintenance and digital support are also available, shaped around what your business needs.', items: ['Maintenance', 'Support', 'Optimisation', 'Updates'], tone: 'violet' }
    ]
  },
  packagesPage: {
    eyebrow: 'Packages', title: 'A digital solution that fits your business.', intro: 'Every business is different. We shape the final solution around your needs, goals and budget.', sectionEyebrow: 'Our commercial structure', sectionTitle: 'A clear starting point for your next digital step.', sectionIntro: 'The packages provide direction. We define the final solution together, based on what your business needs.', packages: [{ name: 'START', price: '25.000', description: 'For small businesses and independent professionals.', fit: 'A clear first step towards a professional online presence.', featured: false }, { name: 'BUSINESS', price: '45.000', description: 'For businesses that want a stronger professional online presence.', fit: 'For businesses ready to present themselves online with more clarity and confidence.', featured: true }, { name: 'TOURISM PRO', price: '65.000', description: 'For hotels, guesthouses, restaurants, tourism businesses, rent-a-car and companies serving national and international customers.', fit: 'A digital foundation for businesses serving local and international customers.', featured: false }], from: 'From', monthlySupport: 'Monthly maintenance and digital support are also available.', faqEyebrow: 'Frequently asked questions', faqTitle: 'The practical details.', faqIntro: 'A few questions that often come up when a business wants to grow digitally.',
    faq: [{ question: 'How long does it take to build a website?', answer: 'Timing depends on the scope and content of the solution. After an initial conversation, we can give a clearer indication for your situation.' }, { question: 'Is hosting included?', answer: 'That depends on the selected solution and project requirements. We explain what is needed before we start.' }, { question: 'Can I use my existing domain?', answer: 'In many cases, yes. We review the current situation with you.' }, { question: 'Will my website work on mobile?', answer: 'Responsive development is part of our approach: the experience is designed for different screen sizes.' }, { question: 'Can WhatsApp be connected?', answer: 'Yes. WhatsApp Business can be included in a suitable website and contact journey.' }, { question: 'Can online reservations be added?', answer: 'Yes, online appointments and reservations can be part of the solution, depending on the workflow you need.' }, { question: 'Do you offer maintenance?', answer: 'Monthly maintenance and digital support are also available.' }, { question: 'Can my website be expanded later?', answer: 'We can build a solution that fits today and can grow with new needs later.' }]
  },
  aboutPage: {
    eyebrow: 'About Morabeza Tech', title: 'Technology with a human touch.', intro: 'Morabeza Tech CV provides digital solutions for businesses and entrepreneurs in Cabo Verde.', missionEyebrow: 'Our mission', missionTitle: 'Visibility that makes contact easier.', missionParagraphs: ['Our goal is simple: help businesses become more visible online and make contact between companies and customers easier.', 'We believe a digital solution does not need to feel complicated. It should be clear for the business owner and for the customer looking for a product, service or place.'], rows: [{ label: '01 / Mission', title: 'More visibility', copy: 'A professional foundation that helps your business be found and understood more easily.' }, { label: '02 / Approach', title: 'Understand before building', copy: 'We look at your business, audience and current online presence before choosing a direction.' }, { label: '03 / Quality', title: 'Clear and considered', copy: 'A modern digital experience with attention to content, usability and responsive quality.' }, { label: '04 / Market', title: 'Praia, Cabo Verde', copy: 'We work with businesses and entrepreneurs in Cabo Verde and how their customers search and connect online.' }, { label: '05 / Future', title: 'Grow digitally', copy: 'A solution that fits today and can keep pace as your business takes its next steps.' }], positionEyebrow: 'Our position', positionTitle: 'Local knowledge, digital focus.', positionIntro: 'Whether it is a restaurant, hotel, salon, shop or another service, more customers are searching online first. We help businesses show up professionally.', mark: 'Soluções digitais para o seu negócio.', location: 'Morabeza Tech CV · Praia', positionCta: 'Talk to us about your business'
  },
  portfolioPage: { eyebrow: 'Portfolio', title: 'Digital experiences that make sense.', intro: 'A selection of concept studies showing how we bring structure, design and contact moments together. Concept Project is clearly stated: these are not real client cases.', filters: ['All', 'Hotel', 'Restaurant', 'Rent-a-car'], projects: [{ slug: 'hotel', label: 'Concept Project', category: 'Boutique hotel', title: 'Casa Atlântica', description: 'A calm, booking-focused digital experience for a coastal hotel.', services: 'Web Design · Responsive development · Reservations', tone: 'ocean' }, { slug: 'restaurant', label: 'Concept Project', category: 'Restaurant', title: 'Maré Restaurante', description: 'An inviting website with menu, location, WhatsApp and reservations.', services: 'Web Design · Google Maps · WhatsApp Business', tone: 'sunset' }, { slug: 'rent-a-car', label: 'Concept Project', category: 'Rent-a-car', title: 'Ilha Drive', description: 'A clear route from vehicle selection to a direct booking request.', services: 'Web Design · Lead generation · Online visibility', tone: 'midnight' }], conceptNote: 'All examples on this page are concept project studies, not presented client results.' },
  contactPage: {
    eyebrow: 'Contact', title: 'Let’s talk about your next digital step.', intro: 'Tell us what you want to achieve. We will think with you about a digital solution that fits your business, goals and budget.', sectionEyebrow: 'Talk to Morabeza Tech', sectionTitle: 'A good first step starts with a clear conversation.', sectionIntro: 'Do you have a concrete idea, or would you like to discover where the opportunities are? Send us a message.', analysisLabel: 'Free digital analysis', freeLabel: 'Free and without obligation.', form: { name: 'Name', company: 'Company name', email: 'Email', phone: 'Phone', subject: 'How can we help?', budget: 'Budget', message: 'Message', messagePlaceholder: 'Briefly tell us what you are looking for.', subjectPlaceholder: 'Choose a subject', budgetPlaceholder: 'Choose a budget', subjects: ['Website', 'Google Business', 'WhatsApp Business', 'Social media', 'Online reservations', 'SEO', 'Maintenance', 'Free digital analysis', 'Other'], budgets: ['From 25,000 CVE', 'From 45,000 CVE', 'From 65,000 CVE', 'I am not sure yet'], consent: 'I consent to my details being used to contact me about this request.', submit: 'Send request', loading: 'Sending your request…', fallback: 'Your email application will open with your request.', success: 'Thank you — we will get back to you as soon as possible.', failure: 'Something went wrong. Please try again or email info@morabezatech.com directly.', required: 'Please complete all required fields.', invalidEmail: 'Please enter a valid email address.' }
  },
  legal: { privacyTitle: 'Privacy policy', privacyIntro: 'Privacy information for contact through morabezatech.com.', privacyEyebrow: 'In brief', privacyHeading: 'Your details stay connected to your request.', privacyParagraphs: ['When you use the contact form, we use the details you provide only to respond to your request. We do not sell personal data and do not use tracking cookies by default.', 'For questions about your data, email info@morabezatech.com. For public use, add the final business and legal details that apply to your situation.'], cookiesTitle: 'Cookie policy', cookiesIntro: 'A transparent explanation of cookie use on morabezatech.com.', cookiesEyebrow: 'No unnecessary tracking', cookiesHeading: 'A light and considered website.', cookiesParagraphs: ['This website does not use analytics or advertising cookies by default. Your browser may process preferences and essential technical functions locally.', 'If analytics or other services are added later, this policy will be updated before that technology is used.'] }
};
