import type { Translation } from './types';

export const nl: Translation = {
  locale: 'nl', localeLabel: 'Nederlands', tagline: 'Soluções digitais para o seu negócio.',
  nav: { home: 'Home', services: 'Diensten', packages: 'Pakketten', about: 'Over ons', contact: 'Contact' },
  footer: { navigation: 'Navigatie', services: 'Diensten', servicesList: [{ label: 'Webdesign', id: 'websites' }, { label: 'Google Business', id: 'google' }, { label: 'WhatsApp Business', id: 'whatsapp' }, { label: 'Facebook & Instagram', id: 'social' }, { label: 'Online reserveringen', id: 'reserveringen' }, { label: 'SEO', id: 'seo' }, { label: 'Onderhoud', id: 'onderhoud' }], contact: 'Contact', privacy: 'Privacybeleid', cookies: 'Cookiebeleid', rights: 'Alle rechten voorbehouden.' },
  common: { analysisCta: 'Gratis digitale analyse', viewWork: 'Bekijk ons werk', viewServices: 'Bekijk alle diensten', viewPackages: 'Bekijk alle pakketten', learnMore: 'Meer over Morabeza Tech', startProject: 'Start jouw project', contactUs: 'Contact opnemen', mostChosen: 'Meest gekozen', languageSelector: 'Taal kiezen', menuOpen: 'Menu openen', menuClose: 'Menu sluiten', next: 'Volgende', backHome: 'Terug naar home', conceptNote: 'Alle voorbeelden zijn conceptprojecten, geen echte klantcases.', location: 'Praia, Cabo Verde', email: 'info@morabezatech.com' },
  home: {
    eyebrow: 'Digitale oplossingen voor moderne bedrijven', title: 'Laat jouw bedrijf groeien met slimme digitale oplossingen.', intro: 'Wij helpen bedrijven en ondernemers in Cabo Verde om online beter zichtbaar te worden, nieuwe klanten te bereiken en digitaal sterker te groeien.', supportingLine: ['Webdesign', 'Online zichtbaarheid', 'Automatisering', 'Digitale groei'],
    positioningEyebrow: 'Meer dan alleen een website', positioningTitle: 'Digitale helderheid die je bedrijf vooruithelpt.', positioningIntro: 'Morabeza Tech ontwikkelt digitale oplossingen die bedrijven helpen professioneler zichtbaar te worden, eenvoudiger bereikbaar te zijn en meer klanten te bereiken.', principles: [{ number: '01', title: 'Professioneel ontwerp', copy: 'Een duidelijke ervaring die vertrouwen uitstraalt.' }, { number: '02', title: 'Slimme technologie', copy: 'De juiste digitale route voor jouw bedrijf.' }, { number: '03', title: 'Gericht op resultaat', copy: 'Online zichtbaar zijn én makkelijk contact maken.' }],
    servicesEyebrow: 'Wat we doen', servicesTitle: 'Digitale oplossingen met een duidelijke bedoeling.', servicesIntro: 'Van je eerste website tot een betere Google-aanwezigheid: we brengen de onderdelen samen die jouw klanten nodig hebben.',
    processEyebrow: 'Onze werkwijze', processTitle: 'Van idee naar een digitale ervaring die werkt.', processIntro: 'Een heldere aanpak, afgestemd op jouw bedrijf, doelgroep en doelen.', process: [{ number: '01', title: 'Analyse', copy: 'We bekijken jouw bedrijf, doelgroep en huidige online aanwezigheid.' }, { number: '02', title: 'Strategie', copy: 'We bepalen wat nodig is om jouw bedrijf professioneel en effectief online te presenteren.' }, { number: '03', title: 'Design', copy: 'We ontwerpen een duidelijke, moderne digitale ervaring passend bij jouw merk.' }, { number: '04', title: 'Development', copy: 'We bouwen een snelle, veilige en responsive website.' }, { number: '05', title: 'Launch & support', copy: 'We publiceren, testen en blijven beschikbaar voor optimalisatie en onderhoud.' }],
    analysisEyebrow: 'Zonder verplichtingen', analysisTitle: 'Begin met een gratis digitale analyse.', analysisIntro: 'We bekijken je Google-aanwezigheid, website, WhatsApp, social media, online reviews en digitale zichtbaarheid. Daarna ontvang je enkele concrete aanbevelingen.', analysisStatus: 'Gratis analyse', analysisItems: ['Google', 'Website', 'WhatsApp', 'Social media', 'Online reviews', 'Digitale zichtbaarheid'], analysisNote: 'Een praktische blik op waar jouw bedrijf online staat en waar kansen liggen.',
    packagesEyebrow: 'Pakketten', packagesTitle: 'Een passende start voor elk type bedrijf.', packagesIntro: 'Elke onderneming is anders. Daarom stemmen we de uiteindelijke oplossing af op jouw wensen, doelen en budget.', monthlySupport: 'Onderhoud en digitale ondersteuning zijn ook beschikbaar op maandbasis.',
    aboutEyebrow: 'Morabeza Tech CV', aboutTitle: 'Technologie met een menselijk gezicht.', aboutIntro: 'Morabeza Tech is een bedrijf voor digitale oplossingen, gericht op bedrijven en ondernemers in Cabo Verde. We helpen bedrijven om online zichtbaar te worden en maken het makkelijker voor klanten om hen te ontdekken, vertrouwen en contacteren.', aboutMark: 'Lokale kennis. Digitale mogelijkheden.', aboutLocation: 'Praia · Cabo Verde', mockupEyebrow: 'Digitale analyse', mockupValue: '+ helderheid',
    finalEyebrow: 'Klaar voor de volgende stap?', finalTitle: 'Klaar om jouw bedrijf sterker online neer te zetten?', finalIntro: 'Vertel ons wat je wilt bereiken. Wij denken mee over een digitale oplossing die past bij jouw bedrijf, doelen en budget.'
  },
  servicesPage: {
    eyebrow: 'Diensten', title: 'Digitale oplossingen die jouw bedrijf verder brengen.', intro: 'Van een professionele website tot betere online zichtbaarheid: we bouwen de digitale basis die klanten helpt om je te vinden, vertrouwen en contacteren.', sectionEyebrow: 'Waar we bij helpen', sectionTitle: 'De juiste onderdelen, samengebracht in één heldere ervaring.', sectionIntro: 'Niet elk bedrijf heeft hetzelfde nodig. Daarom bekijken we eerst waar jouw klanten nu vastlopen en welke digitale oplossing daarbij past.',
    services: [
      { number: '01', title: 'Professionele websites', short: 'Een snelle, responsive en duidelijke digitale basis voor je bedrijf.', detail: 'Een website is vaak het eerste contactmoment met jouw bedrijf. We bouwen een ervaring die past bij je merk en het makkelijk maakt om contact op te nemen.', items: ['Bedrijfswebsites', 'Landing pages', 'Responsive development', 'Performance', 'Onderhoud'], tone: 'blue' },
      { number: '02', title: 'Google Business & Google Maps', short: 'Word gemakkelijker gevonden wanneer klanten naar jouw bedrijf zoeken.', detail: 'Veel klanten zoeken eerst op Google. We helpen om je bedrijfsinformatie helder en professioneel te presenteren, zodat mensen je makkelijker vinden en weten hoe ze je kunnen bereiken.', items: ['Google Business', 'Google Maps', 'Lokale vindbaarheid', 'Bedrijfsinformatie'], tone: 'cyan' },
      { number: '03', title: 'WhatsApp Business', short: 'Maak contact laagdrempelig met een duidelijke route naar WhatsApp.', detail: 'Een goed ingerichte contactflow geeft potentiële klanten minder reden om af te haken.', items: ['WhatsApp Business', 'Contactknoppen', 'Lead generation', 'Duidelijke contactroute'], tone: 'gold' },
      { number: '04', title: 'Facebook & Instagram', short: 'Een consistente digitale aanwezigheid die vertrouwen uitstraalt.', detail: 'We helpen om je digitale aanwezigheid professioneel te laten aansluiten op je website en Google-profiel.', items: ['Facebook', 'Instagram', 'Digitale aanwezigheid', 'Contentstructuur'], tone: 'violet' },
      { number: '05', title: 'Online afspraken & reserveringen', short: 'Maak het eenvoudiger om een afspraak, tafel, kamer of voertuig aan te vragen.', detail: 'We denken mee over een online route die past bij de manier waarop jouw bedrijf werkt.', items: ['Online afspraken', 'Reserveringen', 'Aanvraagflows', 'Contactformulieren'], tone: 'blue' },
      { number: '06', title: 'Reviews & online reputatie', short: 'Geef potentiële klanten meer vertrouwen in jouw bedrijf.', detail: 'Reviews helpen potentiële klanten om een beeld te vormen. We helpen met de digitale plekken en contactmomenten waar online reputatie onderdeel van de ervaring wordt.', items: ['Online reviews', 'Reputatie', 'Review-flow', 'Vertrouwen'], tone: 'cyan' },
      { number: '07', title: 'SEO & online vindbaarheid', short: 'Een goede digitale basis maakt het makkelijker om gevonden te worden.', detail: 'We letten op structuur, informatie en lokale context voor bedrijven in Cabo Verde.', items: ['SEO', 'Online vindbaarheid', 'Lokale context', 'Informatiearchitectuur'], tone: 'gold' },
      { number: '08', title: 'Website onderhoud & support', short: 'Houd je digitale basis duidelijk, actueel en bruikbaar.', detail: 'Onderhoud en digitale ondersteuning zijn ook beschikbaar op maandbasis, afgestemd op wat jouw bedrijf nodig heeft.', items: ['Onderhoud', 'Ondersteuning', 'Optimalisatie', 'Updates'], tone: 'violet' }
    ]
  },
  packagesPage: {
    eyebrow: 'Pakketten', title: 'Een digitale oplossing die past bij jouw bedrijf.', intro: 'Elke onderneming is anders. Daarom stemmen we de uiteindelijke oplossing af op jouw wensen, doelen en budget.', sectionEyebrow: 'Onze commerciële structuur', sectionTitle: 'Een helder vertrekpunt voor jouw digitale volgende stap.', sectionIntro: 'De pakketten geven richting. De uiteindelijke oplossing bepalen we samen op basis van wat jouw bedrijf nodig heeft.', packages: [{ name: 'START', price: '25.000', description: 'Voor kleine ondernemingen en zelfstandigen.', fit: 'Een heldere eerste stap naar een professionele online aanwezigheid.', featured: false }, { name: 'BUSINESS', price: '45.000', description: 'Voor bedrijven die professioneel online zichtbaar willen zijn.', fit: 'Voor ondernemingen die hun bedrijf sterker en duidelijker online willen presenteren.', featured: true }, { name: 'TOURISM PRO', price: '65.000', description: 'Voor hotels, guesthouses, restaurants, toeristische bedrijven en bedrijven die veel internationale klanten bedienen.', fit: 'Een digitale basis voor bedrijven die nationale en internationale klanten bedienen.', featured: false }], from: 'Vanaf', monthlySupport: 'Onderhoud en digitale ondersteuning zijn ook beschikbaar op maandbasis.', faqEyebrow: 'Veelgestelde vragen', faqTitle: 'Praktisch geregeld.', faqIntro: 'Een paar vragen die vaak terugkomen wanneer een bedrijf digitaal sterker wil worden.',
    faq: [{ question: 'Hoe lang duurt het bouwen van een website?', answer: 'De doorlooptijd hangt af van de omvang en inhoud van de oplossing. Na een eerste gesprek kunnen we beter aangeven wat passend is voor jouw situatie.' }, { question: 'Is hosting inbegrepen?', answer: 'Dat hangt af van de gekozen oplossing en projectvereisten. We bespreken duidelijk wat nodig is voordat we starten.' }, { question: 'Kan mijn bestaande domein worden gebruikt?', answer: 'Ja, een bestaand domein kan in veel gevallen worden gebruikt. We bekijken de huidige situatie samen.' }, { question: 'Werkt mijn website op mobiel?', answer: 'Responsive development is onderdeel van onze aanpak: de ervaring wordt ontworpen voor verschillende schermformaten.' }, { question: 'Kan WhatsApp worden gekoppeld?', answer: 'Ja. WhatsApp Business is een van de digitale oplossingen die we kunnen meenemen in een passende website en contactroute.' }, { question: 'Kunnen online reserveringen worden toegevoegd?', answer: 'Ja, online afspraken en reserveringen kunnen onderdeel worden van de oplossing, afhankelijk van de gewenste workflow.' }, { question: 'Bieden jullie onderhoud aan?', answer: 'Onderhoud en digitale ondersteuning zijn ook beschikbaar op maandbasis.' }, { question: 'Kan mijn website later worden uitgebreid?', answer: 'We kunnen een oplossing opbouwen die past bij jouw huidige doelen en later kan meegroeien met nieuwe wensen.' }]
  },
  aboutPage: {
    eyebrow: 'Over Morabeza Tech', title: 'Technologie met een menselijk gezicht.', intro: 'Morabeza Tech CV biedt digitale oplossingen voor bedrijven en ondernemers in Cabo Verde.', missionEyebrow: 'Onze missie', missionTitle: 'Zichtbaarheid die contact makkelijker maakt.', missionParagraphs: ['Ons doel is eenvoudig: bedrijven helpen om online beter zichtbaar te worden en het contact tussen ondernemingen en klanten gemakkelijker te maken.', 'We geloven dat een digitale oplossing niet ingewikkeld hoeft te voelen. Ze moet helder zijn voor de ondernemer én voor de klant die op zoek is naar een product, dienst of plek.'], rows: [{ label: '01 / Missie', title: 'Meer zichtbaarheid', copy: 'Een professionele basis waardoor jouw bedrijf beter gevonden en begrepen wordt.' }, { label: '02 / Aanpak', title: 'Eerst begrijpen, dan bouwen', copy: 'We bekijken je bedrijf, doelgroep en huidige online aanwezigheid voordat we een richting kiezen.' }, { label: '03 / Kwaliteit', title: 'Duidelijk en zorgvuldig', copy: 'Een moderne digitale ervaring met aandacht voor inhoud, gebruiksgemak en responsive kwaliteit.' }, { label: '04 / Markt', title: 'Praia, Cabo Verde', copy: 'We richten ons op bedrijven en ondernemers in Cabo Verde en de manier waarop hun klanten online zoeken en contact maken.' }, { label: '05 / Toekomst', title: 'Digitaal sterker groeien', copy: 'Een oplossing die vandaag past en kan meegroeien wanneer jouw bedrijf nieuwe stappen zet.' }], positionEyebrow: 'Onze positie', positionTitle: 'Lokaal geworteld, digitaal gericht.', positionIntro: 'Of het nu gaat om een restaurant, hotel, salon, winkel of andere dienst: potentiële klanten zoeken steeds vaker eerst online. Wij helpen bedrijven om daar professioneel aanwezig te zijn.', mark: 'Soluções digitais para o seu negócio.', location: 'Morabeza Tech CV · Praia', positionCta: 'Bespreek jouw bedrijf met ons'
  },
  contactPage: {
    eyebrow: 'Contact', title: 'Laten we praten over jouw volgende digitale stap.', intro: 'Vertel ons wat je wilt bereiken. We denken mee over een digitale oplossing die past bij jouw bedrijf, doelen en budget.', sectionEyebrow: 'Praat met Morabeza Tech', sectionTitle: 'Een goede eerste stap begint met een helder gesprek.', sectionIntro: 'Heb je al een concreet idee of wil je eerst weten waar de kansen liggen? Stuur ons een bericht.', analysisLabel: 'Gratis digitale analyse', freeLabel: 'Gratis en zonder verplichtingen.', form: { name: 'Naam', company: 'Bedrijfsnaam', email: 'E-mail', phone: 'Telefoonnummer', subject: 'Waar kunnen we mee helpen?', budget: 'Budget', message: 'Bericht', messagePlaceholder: 'Vertel kort waar je hulp bij zoekt.', subjectPlaceholder: 'Kies een onderwerp', budgetPlaceholder: 'Kies een budget', subjects: ['Website', 'Google Business', 'WhatsApp Business', 'Social Media', 'Online reserveringen', 'SEO', 'Onderhoud', 'Gratis digitale analyse', 'Anders'], budgets: ['Vanaf 25.000 CVE', 'Vanaf 45.000 CVE', 'Vanaf 65.000 CVE', 'Ik weet het nog niet'], consent: 'Ik geef toestemming om mijn gegevens te gebruiken om contact met mij op te nemen over deze aanvraag.', submit: 'Verstuur aanvraag', loading: 'Aanvraag wordt verstuurd…', fallback: 'Je e-mailprogramma wordt geopend met je aanvraag.', success: 'Bedankt — we nemen zo snel mogelijk contact met je op.', failure: 'Er ging iets mis. Probeer het opnieuw of mail rechtstreeks naar info@morabezatech.com.', required: 'Vul alle verplichte velden in.', invalidEmail: 'Vul een geldig e-mailadres in.' }
  },
  legal: { privacyTitle: 'Privacybeleid', privacyIntro: 'Deze pagina bevat de privacy-informatie voor contact via morabezatech.com.', privacyEyebrow: 'In het kort', privacyHeading: 'Jouw gegevens blijven voor jouw aanvraag.', privacyParagraphs: ['Wanneer je het contactformulier gebruikt, gebruiken we de ingevulde gegevens alleen om contact op te nemen over jouw aanvraag. We verkopen persoonsgegevens niet en plaatsen standaard geen trackingcookies.', 'Voor vragen over je gegevens kun je mailen naar info@morabezatech.com. Voeg voor live gebruik de definitieve bedrijfs- en wettelijke gegevens toe die op jouw situatie van toepassing zijn.'], cookiesTitle: 'Cookiebeleid', cookiesIntro: 'Een transparante uitleg over het gebruik van cookies op morabezatech.com.', cookiesEyebrow: 'Geen onnodige tracking', cookiesHeading: 'De website is ontworpen om licht en rustig te blijven.', cookiesParagraphs: ['Deze website gebruikt standaard geen analytics- of advertentiecookies. De voorkeuren van je browser en noodzakelijke technische werking kunnen wel lokaal door de browser worden verwerkt.', 'Als er later analytics of andere diensten worden toegevoegd, wordt dit beleid bijgewerkt voordat die technologie wordt gebruikt.'] }
};
