import type { Translation } from './types';

export const pt: Translation = {
  locale: 'pt', localeLabel: 'Português', tagline: 'Soluções digitais para o seu negócio.',
  nav: { home: 'Início', services: 'Serviços', packages: 'Pacotes', about: 'Sobre nós', contact: 'Contacto' },
  footer: { navigation: 'Navegação', services: 'Serviços', servicesList: [{ label: 'Web Design', id: 'websites' }, { label: 'Google Business', id: 'google' }, { label: 'WhatsApp Business', id: 'whatsapp' }, { label: 'Facebook & Instagram', id: 'social' }, { label: 'Reservas online', id: 'reserveringen' }, { label: 'SEO', id: 'seo' }, { label: 'Manutenção', id: 'onderhoud' }], contact: 'Contacto', privacy: 'Política de privacidade', cookies: 'Política de cookies', rights: 'Todos os direitos reservados.' },
  common: { analysisCta: 'Análise digital gratuita', viewWork: 'Ver o nosso trabalho', viewServices: 'Ver todos os serviços', viewPackages: 'Ver todos os pacotes', learnMore: 'Mais sobre a Morabeza Tech', startProject: 'Iniciar o seu projeto', contactUs: 'Entrar em contacto', mostChosen: 'Recomendado', languageSelector: 'Escolher idioma', menuOpen: 'Abrir menu', menuClose: 'Fechar menu', next: 'Seguinte', backHome: 'Voltar ao início', conceptNote: 'Todos os exemplos são projetos conceptuais, não casos reais de clientes.', location: 'Praia, Cabo Verde', email: 'info@morabezatech.com' },
  home: {
    eyebrow: 'Soluções digitais para empresas modernas', title: 'Faça o seu negócio avançar com tecnologia inteligente.', intro: 'A Morabeza Tech ajuda empresas em Cabo Verde a utilizar a tecnologia de forma prática, trabalhar melhor, ganhar visibilidade e crescer no digital.', supportingLine: ['Websites & plataformas', 'Cloud & infraestrutura', 'Automação', 'Crescimento digital'],
    positioningEyebrow: 'Mais do que um website', positioningTitle: 'Clareza digital para fazer o seu negócio avançar.', positioningIntro: 'A Morabeza Tech desenvolve soluções digitais que ajudam as empresas a apresentar-se melhor, a ser mais fáceis de contactar e a alcançar mais clientes.', principles: [{ number: '01', title: 'Design profissional', copy: 'Uma experiência clara que transmite confiança.' }, { number: '02', title: 'Tecnologia inteligente', copy: 'A solução digital certa para o seu negócio.' }, { number: '03', title: 'Foco no resultado', copy: 'Mais visibilidade e contacto mais simples.' }],
    servicesEyebrow: 'O que fazemos', servicesTitle: 'Soluções digitais com uma finalidade clara.', servicesIntro: 'Do primeiro website a uma presença mais forte no Google: reunimos os elementos de que os seus clientes precisam.',
    processEyebrow: 'A nossa abordagem', processTitle: 'Da ideia a uma experiência digital que funciona.', processIntro: 'Um processo claro, adaptado ao seu negócio, ao seu público e aos seus objetivos.', process: [{ number: '01', title: 'Análise', copy: 'Analisamos o seu negócio, o seu público e a sua presença digital atual.' }, { number: '02', title: 'Estratégia', copy: 'Definimos o que é necessário para apresentar o seu negócio online de forma profissional e eficaz.' }, { number: '03', title: 'Design', copy: 'Criamos uma experiência digital clara e moderna, adequada à sua marca.' }, { number: '04', title: 'Desenvolvimento', copy: 'Construímos um website rápido, seguro e responsivo.' }, { number: '05', title: 'Lançamento e suporte', copy: 'Publicamos, testamos e continuamos disponíveis para otimização e manutenção.' }],
    analysisEyebrow: 'Sem compromisso', analysisTitle: 'Comece com uma análise digital gratuita.', analysisIntro: 'Analisamos a sua presença no Google, o website, o WhatsApp, as redes sociais, as avaliações online e a visibilidade digital. Depois, apresentamos algumas recomendações concretas.', analysisStatus: 'Análise gratuita', analysisItems: ['Google', 'Website', 'WhatsApp', 'Redes sociais', 'Avaliações online', 'Visibilidade digital'], analysisNote: 'Uma visão prática da presença online do seu negócio e das oportunidades existentes.',
    packagesEyebrow: 'Pacotes', packagesTitle: 'Um ponto de partida para cada tipo de negócio.', packagesIntro: 'Cada empresa é diferente. Por isso, adaptamos a solução final às suas necessidades, objetivos e orçamento.', monthlySupport: 'Também disponibilizamos manutenção e suporte digital numa base mensal.',
    aboutEyebrow: 'Morabeza Tech CV', aboutTitle: 'Tecnologia com um rosto humano.', aboutIntro: 'A Morabeza Tech é uma empresa de soluções digitais focada em empresas e empreendedores em Cabo Verde. Ajudamos os negócios a ganhar visibilidade online e facilitamos o contacto com os seus clientes.', aboutMark: 'Conhecimento local. Possibilidades digitais.', aboutLocation: 'Praia · Cabo Verde', mockupEyebrow: 'Análise digital', mockupValue: '+ clareza',
    finalEyebrow: 'Pronto para o próximo passo?', finalTitle: 'Pronto para fortalecer a presença online do seu negócio?', finalIntro: 'Conte-nos o que pretende alcançar. Pensamos consigo numa solução digital adequada ao seu negócio, aos seus objetivos e ao seu orçamento.'
  },
  servicesPage: {
    eyebrow: 'Serviços', title: 'Soluções digitais para levar o seu negócio mais longe.', intro: 'De um website profissional a uma melhor visibilidade online: construímos a base digital que ajuda os clientes a encontrar, conhecer e contactar o seu negócio.', sectionEyebrow: 'Como podemos ajudar', sectionTitle: 'Os elementos certos reunidos numa experiência clara.', sectionIntro: 'Cada negócio tem necessidades diferentes. Começamos por compreender onde os seus clientes encontram dificuldades e qual a solução digital mais adequada.',
    services: [
      { number: '01', title: 'Websites profissionais', short: 'Uma base digital rápida, responsiva e clara para o seu negócio.', detail: 'O website é muitas vezes o primeiro contacto com a sua empresa. Criamos uma experiência adequada à sua marca e que torna o contacto mais simples.', items: ['Websites empresariais', 'Landing pages', 'Desenvolvimento responsivo', 'Performance', 'Manutenção'], tone: 'blue' },
      { number: '02', title: 'Google Business & Google Maps', short: 'Seja encontrado com mais facilidade quando os clientes procuram o seu negócio.', detail: 'Muitos clientes começam a sua pesquisa no Google. Ajudamos a apresentar a informação da sua empresa de forma clara e profissional.', items: ['Google Business', 'Google Maps', 'Visibilidade local', 'Informação empresarial'], tone: 'cyan' },
      { number: '03', title: 'WhatsApp Business', short: 'Facilite o contacto através de uma ligação clara ao WhatsApp.', detail: 'Uma boa experiência de contacto reduz as dúvidas e torna mais simples iniciar uma conversa com potenciais clientes.', items: ['WhatsApp Business', 'Botões de contacto', 'Geração de leads', 'Percurso de contacto'], tone: 'gold' },
      { number: '04', title: 'Facebook & Instagram', short: 'Uma presença digital consistente que transmite confiança.', detail: 'Ajudamos a alinhar a presença nas redes sociais com o website e o perfil no Google.', items: ['Facebook', 'Instagram', 'Presença digital', 'Estrutura de conteúdo'], tone: 'violet' },
      { number: '05', title: 'Marcações e reservas online', short: 'Facilite pedidos de marcação, mesas, quartos ou veículos.', detail: 'Pensamos consigo num percurso online adequado à forma como o seu negócio funciona.', items: ['Marcações online', 'Reservas', 'Formulários de pedido', 'Formulários de contacto'], tone: 'blue' },
      { number: '06', title: 'Avaliações e reputação online', short: 'Ajude os potenciais clientes a confiar no seu negócio.', detail: 'As avaliações ajudam a formar uma opinião. Consideramos os espaços digitais onde a reputação faz parte da experiência.', items: ['Avaliações online', 'Reputação', 'Fluxo de avaliações', 'Confiança'], tone: 'cyan' },
      { number: '07', title: 'SEO e visibilidade online', short: 'Uma boa base digital torna mais fácil ser encontrado.', detail: 'Damos atenção à estrutura, à informação e ao contexto local dos negócios em Cabo Verde.', items: ['SEO', 'Visibilidade online', 'Contexto local', 'Arquitetura de informação'], tone: 'gold' },
      { number: '08', title: 'Manutenção e suporte de websites', short: 'Mantenha a sua base digital clara, atualizada e funcional.', detail: 'Também disponibilizamos manutenção e suporte digital numa base mensal, de acordo com as necessidades do seu negócio.', items: ['Manutenção', 'Suporte', 'Otimização', 'Atualizações'], tone: 'violet' }
    ]
  },
  packagesPage: {
    eyebrow: 'Pacotes', title: 'Uma solução digital adequada ao seu negócio.', intro: 'Oferecemos três pacotes. Fale connosco para descobrir qual a solução mais adequada à sua empresa.', sectionEyebrow: 'A nossa estrutura comercial', sectionTitle: 'Um ponto de partida claro para o seu próximo passo digital.', sectionIntro: 'A solução final depende dos seus objetivos, tecnologia e maturidade digital. Definimo-la em conjunto.', packages: [{ name: 'START', description: 'Para pequenos negócios e profissionais independentes que precisam de uma base digital profissional.', fit: 'Um primeiro passo claro para uma presença digital profissional.', featured: false }, { name: 'BUSINESS', description: 'Para empresas que procuram uma solução tecnológica mais completa, ligada e profissional.', fit: 'Para organizações que querem trabalhar melhor no digital.', featured: true }, { name: 'TOURISM PRO', description: 'Para hotéis, guesthouses, restaurantes, turismo, rent-a-car e negócios de hospitalidade.', fit: 'Para empresas que recebem visitantes nacionais e internacionais.', featured: false }], consultationTitle: 'Qual é o pacote certo para o seu negócio?', consultationIntro: 'Conte-nos brevemente sobre a sua empresa. Recomendamos a solução mais adequada aos seus objetivos e maturidade digital.', consultationCta: 'Pedir aconselhamento', monthlySupport: 'Também disponibilizamos manutenção e suporte digital numa base mensal.', faqEyebrow: 'Perguntas frequentes', faqTitle: 'Tudo mais claro.', faqIntro: 'Algumas perguntas frequentes de empresas que querem fortalecer a sua presença digital.',
    faq: [{ question: 'Quanto tempo demora a criar um website?', answer: 'O prazo depende da dimensão e do conteúdo da solução. Depois de uma primeira conversa, podemos indicar melhor o que é adequado para a sua situação.' }, { question: 'O alojamento está incluído?', answer: 'Depende da solução escolhida e dos requisitos do projeto. Explicamos claramente o que é necessário antes de começar.' }, { question: 'Posso utilizar o meu domínio atual?', answer: 'Sim, na maioria dos casos é possível utilizar um domínio existente. Analisamos a situação atual consigo.' }, { question: 'O website funciona no telemóvel?', answer: 'O desenvolvimento responsivo faz parte da nossa abordagem: a experiência é pensada para diferentes tamanhos de ecrã.' }, { question: 'É possível ligar o WhatsApp?', answer: 'Sim. O WhatsApp Business pode ser incluído numa solução e num percurso de contacto adequado.' }, { question: 'É possível adicionar reservas online?', answer: 'Sim, marcações e reservas online podem fazer parte da solução, dependendo do fluxo pretendido.' }, { question: 'Disponibilizam manutenção?', answer: 'Também disponibilizamos manutenção e suporte digital numa base mensal.' }, { question: 'O website pode ser ampliado mais tarde?', answer: 'Podemos criar uma solução adequada aos objetivos atuais e preparada para acompanhar novas necessidades.' }]
  },
  aboutPage: {
    eyebrow: 'Sobre a Morabeza Tech', title: 'Tecnologia com um rosto humano.', intro: 'A Morabeza Tech CV oferece soluções digitais para empresas e empreendedores em Cabo Verde.', missionEyebrow: 'A nossa missão', missionTitle: 'Visibilidade que facilita o contacto.', missionParagraphs: ['O nosso objetivo é simples: ajudar os negócios a ganhar visibilidade online e facilitar o contacto entre empresas e clientes.', 'Acreditamos que uma solução digital não precisa de ser complicada. Deve ser clara para o empresário e para o cliente que procura um produto, serviço ou lugar.'], rows: [{ label: '01 / Missão', title: 'Mais visibilidade', copy: 'Uma base profissional para que o seu negócio seja encontrado e compreendido com mais facilidade.' }, { label: '02 / Abordagem', title: 'Compreender antes de construir', copy: 'Analisamos o seu negócio, o público e a presença digital atual antes de escolher uma direção.' }, { label: '03 / Qualidade', title: 'Clareza e cuidado', copy: 'Uma experiência moderna com atenção ao conteúdo, à facilidade de utilização e à qualidade responsiva.' }, { label: '04 / Mercado', title: 'Praia, Cabo Verde', copy: 'Trabalhamos com empresas e empreendedores em Cabo Verde e com a forma como os seus clientes procuram e contactam online.' }, { label: '05 / Futuro', title: 'Crescer no digital', copy: 'Uma solução adequada para hoje e capaz de acompanhar os próximos passos do seu negócio.' }], positionEyebrow: 'A nossa posição', positionTitle: 'Conhecimento local, visão digital.', positionIntro: 'Seja um restaurante, hotel, salão, loja ou outro serviço: cada vez mais clientes procuram primeiro online. Ajudamos os negócios a estar presentes de forma profissional.', mark: 'Soluções digitais para o seu negócio.', location: 'Morabeza Tech CV · Praia', positionCta: 'Fale connosco sobre o seu negócio'
  },
  contactPage: {
    eyebrow: 'Contacto', title: 'Vamos falar sobre o seu próximo passo digital.', intro: 'Conte-nos o que pretende alcançar. Pensamos consigo numa solução digital adequada ao seu negócio e aos seus objetivos.', sectionEyebrow: 'Fale com a Morabeza Tech', sectionTitle: 'Um bom primeiro passo começa com uma conversa clara.', sectionIntro: 'Já tem uma ideia concreta ou quer primeiro descobrir onde existem oportunidades? Envie-nos uma mensagem.', analysisLabel: 'Análise digital gratuita', freeLabel: 'Gratuita e sem compromisso.', form: { name: 'Nome', company: 'Nome da empresa', email: 'E-mail', phone: 'Telefone', subject: 'Como podemos ajudar?', budget: 'Orçamento', message: 'Mensagem', messagePlaceholder: 'Conte-nos brevemente o que procura.', subjectPlaceholder: 'Escolha um assunto', budgetPlaceholder: 'Escolha uma direção', subjects: ['Website', 'Google Business', 'WhatsApp Business', 'Redes sociais', 'Reservas online', 'SEO', 'Manutenção', 'Análise digital gratuita', 'Outro'], budgets: ['Base digital profissional', 'Presença online completa', 'Turismo e clientes internacionais', 'Ainda não sei'], consent: 'Autorizo a utilização dos meus dados para ser contactado sobre este pedido.', submit: 'Enviar pedido', loading: 'A enviar o pedido…', fallback: '', success: 'Obrigado. O seu pedido foi enviado. Entraremos em contacto consigo o mais breve possível.', failure: 'Ocorreu um erro. Tente novamente. Também pode contactar-nos através de info@morabezatech.com.', required: 'Preencha todos os campos obrigatórios.', invalidEmail: 'Introduza um endereço de e-mail válido.' }
  },
  legal: { privacyTitle: 'Política de privacidade', privacyIntro: 'Informação sobre privacidade para contactos através de morabezatech.com.', privacyEyebrow: 'Em resumo', privacyHeading: 'Os seus dados ficam associados ao seu pedido.', privacyParagraphs: ['Quando utiliza o formulário de contacto, utilizamos os dados preenchidos apenas para responder ao seu pedido. Não vendemos dados pessoais nem utilizamos cookies de rastreamento por defeito.', 'Para questões sobre os seus dados, escreva para info@morabezatech.com. Para utilização pública, acrescente os dados legais definitivos aplicáveis ao seu caso.'], cookiesTitle: 'Política de cookies', cookiesIntro: 'Uma explicação transparente sobre a utilização de cookies em morabezatech.com.', cookiesEyebrow: 'Sem rastreamento desnecessário', cookiesHeading: 'Um website leve e tranquilo.', cookiesParagraphs: ['Este website não utiliza por defeito cookies de analytics ou publicidade. O seu navegador pode processar localmente preferências e elementos técnicos necessários ao funcionamento.', 'Se forem adicionados analytics ou outros serviços no futuro, esta política será atualizada antes da utilização dessa tecnologia.'] }
};
